# -*- coding: utf-8 -*-
"""download_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFRUYkLLL58wGGttSkWwlHUOOhsvO5qQ
"""

import requests
import os
import zipfile

# 下载文件函数
def download_file(url):
    response = requests.get(url, allow_redirects=True)
    filename = os.path.basename(url)
    with open(filename, 'wb') as file:
        file.write(response.content)
    print(f"{filename} 下载完成")


# 解压缩
def unzip_file(zip_file_path, extract_to_dir='.'):
    """
    解压指定的 ZIP 文件到指定目录。如果没有提供目标目录，则解压到ZIP文件所在的目录。

    参数:
    zip_file_path (str): ZIP 文件的路径
    extract_to_dir (str): 解压后的目标目录（可选）。如果未指定，默认为 ZIP 文件所在目录
    """
    if extract_to_dir is None:
        # 如果没有提供目标解压目录，使用ZIP文件的所在目录
        extract_to_dir = os.path.dirname(zip_file_path)

    # 确保目标目录存在
    if not os.path.exists(extract_to_dir):
        os.makedirs(extract_to_dir)

    # 解压 ZIP 文件
    with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
        zip_ref.extractall(extract_to_dir)  # 解压所有文件
        print(f"已解压 '{zip_file_path}' 到 '{extract_to_dir}'")

import requests
import os

# 文件 URLs
urls = [
    "https://github.com/xyt556/Data/raw/main/font_colab.ipynb",
    "https://github.com/xyt556/Data/raw/main/set_font.ipynb",
    "https://github.com/xyt556/Data/raw/main/download_file.ipynb"
]

# 下载文件
for url in urls:
    download_file(url)

# Commented out IPython magic to ensure Python compatibility.
# %run font_colab.ipynb

# Commented out IPython magic to ensure Python compatibility.
# %run set_font.ipynb